In [152]:
import numpy as np
path='dump_match_pairs_kitti_2048/0000000062_0000000063_matches.npz'
npz=np.load(path)

In [153]:
npz.files

['keypoints0', 'keypoints1', 'matches', 'match_confidence']

In [154]:
npz['keypoints0'][:10]

array([[ 464.,    8.],
       [ 780.,    8.],
       [ 878.,    8.],
       [1093.,    8.],
       [1310.,    8.],
       [1328.,    8.],
       [ 834.,    9.],
       [1340.,    9.],
       [1493.,    9.],
       [ 694.,   10.]], dtype=float32)

In [155]:
k1=npz['keypoints0']
k2=npz['keypoints1']
matches=npz['matches'].reshape(-1,1)

In [156]:
npz["match_confidence"][:20]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 9.5888823e-01, 7.2403812e-01,
       9.5913792e-01, 0.0000000e+00, 8.1372678e-02, 5.5132178e-04,
       8.6664611e-01, 9.5898247e-01, 9.5918000e-01, 9.5992130e-01],
      dtype=float32)

In [157]:
k1_matches=np.concatenate((k1, matches), axis=1)
k1_matches=k1_matches[k1_matches[:, 2]!=-1]
k1_matches[:5]

array([[1030.,   10.,    4.],
       [1165.,   10.,    9.],
       [ 607.,   11.,    3.],
       [  14.,   13.,   11.],
       [ 806.,   13.,    8.]])

In [158]:
k2_matches=k2[k1_matches[:,2].astype(np.int64)]

In [159]:
k1_matches=k1_matches[:,[0,1]]
matching_points=np.concatenate((k1_matches, k2_matches), axis=1)

In [160]:
print(len(matching_points))
print("Matching points: {}".format(matching_points[:10]))

1034
Matching points: [[1030.   10. 1035.    8.]
 [1165.   10. 1171.    9.]
 [ 607.   11.  606.    8.]
 [  14.   13.    8.   10.]
 [ 806.   13.  809.    9.]
 [ 596.   14.  595.    9.]
 [ 982.   14.  989.   10.]
 [1113.   14. 1120.   12.]
 [ 706.   15.  708.   11.]
 [ 737.   15.  739.   12.]]


In [161]:
threshold=38.92
x_diff=np.square(matching_points[:, 0]-matching_points[:, 2])
y_diff=np.square(matching_points[:, 1]-matching_points[:, 3])
np.sum(np.sqrt(x_diff+y_diff)>threshold)

42

In [162]:
import cv2
k1_matches= np.int64(k1_matches)
k2_matches= np.int64(k2_matches)
K=np.array([[0.58, 0, 0.5],
            [0, 1.92, 0.5,],
            [0, 0, 1]], dtype=np.float32)

In [163]:
E=cv2.findEssentialMat(k1_matches, k2_matches, cameraMatrix=K)

In [164]:
E[0]

array([[ 2.92022981e-09, -7.40913124e-04,  8.61759488e-02],
       [ 7.41254697e-04, -7.31173331e-06, -7.01835563e-01],
       [-8.61150070e-02,  7.01843042e-01, -7.18013034e-06]])

In [168]:
R=cv2.recoverPose(E[0], k1_matches, k2_matches)

In [173]:
print(R[1])
print(R[2])

[[ 9.99999996e-01 -8.68207025e-05 -7.80342550e-07]
 [ 8.68206944e-05  9.99999996e-01 -1.03263178e-05]
 [ 7.81239085e-07  1.03262500e-05  1.00000000e+00]]
[[-0.99254537]
 [-0.12187118]
 [-0.00104907]]
